package com.example.lenovo.gmegeeknews.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.lenovo.gmegeeknews.bean.daobean.GeekCollectionDaoBean;

import com.example.lenovo.gmegeeknews.dao.GeekCollectionDaoBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig geekCollectionDaoBeanDaoConfig;

    private final GeekCollectionDaoBeanDao geekCollectionDaoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        geekCollectionDaoBeanDaoConfig = daoConfigMap.get(GeekCollectionDaoBeanDao.class).clone();
        geekCollectionDaoBeanDaoConfig.initIdentityScope(type);

        geekCollectionDaoBeanDao = new GeekCollectionDaoBeanDao(geekCollectionDaoBeanDaoConfig, this);

        registerDao(GeekCollectionDaoBean.class, geekCollectionDaoBeanDao);
    }
    
    public void clear() {
        geekCollectionDaoBeanDaoConfig.clearIdentityScope();
    }

    public GeekCollectionDaoBeanDao getGeekCollectionDaoBeanDao() {
        return geekCollectionDaoBeanDao;
    }

}
